services:

  mysql:
    image: mysql:5.7
    container_name: mysql57
    environment:
      - MYSQL_ROOT_PASSWORD=smile
      - TZ=Asia/Shanghai
    volumes:
      - /opt/mysql57/data:/var/lib/mysql
      - /opt/mysql57/my.cnf:/etc/my.cnf
    ports:
      - 3307:3306
    # restart: always
    networks:
      net_d1:
        ipv4_address: 172.20.0.20

# networks:
#   net_d1:
#     external: true
