services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 2024:2024
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /opt/vitepress/docs/.vitepress/dist:/usr/share/nginx/html/dist
      - /opt/web:/usr/share/nginx/html/web
    networks:
      - net_d1
    # depends_on:
    #   - jira
    #   - confluence

# networks:
#   net_d1:
#     external: true

