services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /opt/vitepress/docs/.vitepress/dist:/usr/share/nginx/html/dist
      - /opt/web:/usr/share/nginx/html/web
    network_mode: "host"
    # depends_on:
    #   - jira
    #   - confluence

# networks:
#   net_d1:
#     external: true

