services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    # restart: no
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker
      
  jenkins:
    # build: .
    image: myjenkins-blueocean:lts
    container_name: jenkins
    depends_on:
      - jenkins-docker
    ports:
      - 8081:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      jenkins:
        aliases:
          - docker

networks:
  jenkins:
    external: true
volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    external: true
  docker-data:
    external: true